CREATE TABLE [dbo].[DIRECTIVE]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [PhoneNum] NVARCHAR(50) NOT NULL, 
    [Id_Alumni] INT NOT NULL, 
    CONSTRAINT [FK_DIRECTIVE_ALUMNI] FOREIGN KEY (Id_Alumni) REFERENCES [ALUMNI]([Id])
)
