CREATE TABLE [dbo].[JOINED]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Id_Alumni] INT NOT NULL,
	[Cod_Subject] INT NOT NULL,
	CONSTRAINT [FK_JOINED_ALUMNI] FOREIGN KEY ([Id_Alumni]) REFERENCES [ALUMNI]([Id]),
	CONSTRAINT [FK_JOINED_SUBJECT] FOREIGN KEY ([Cod_Subject]) REFERENCES [SUBJECT]([Cod])
)
